# from lm import GPT2LM

# model = GPT2LM("./calm/finetune/models/gpt/model/epoch00/")
# print(model.generate("[CLS] observation [SEP] action [SEP] next observation [SEP]", k=30))
# string = '[CLS] You are at the start of your journey. [SEP] begin journey [SEP] NEVERMORE An Interactive Gothic by Nate Cull, 2000. Type ABOUT for instructions. Release 10 / Serial number 000928 / Inform v6.21 Library 6/10 Study (on the velvet couch) Stone walls, wreathed in shadows and velvet curtains, rise into the gloom overhead. The old oak writing desk -- once your father\'s, now your own -- is wedged beneath the window lattice, with a velvet couch before it. A low fire smoulders in its ancient hearth. To the southeast, a bust of Pallas sits atop an arch with darkness beyond. NEVERMORE is a work of Interactive Fiction by Nate Cull (culln@xtra.co.nz), written for the 2000 IF Competition, and based very loosely on the poem "The Raven" by Edgar Allan Poe. All box quotes are from the www.eserver.org text of the poem. Everything else is original, bears no relation to any known literary work or historical fact, and is quite probably indicative of some deep unresolved psychological trauma in the author\'s childhood. For help at any time, type HINT. To see if the game is still winnable, type WINNABLE. Thanks to: the ifMUD gang at http://ifmud.port4000.com for support with Inform coding lore and a constant supply of monkey jokes; Admiral Jota and the Emily who is not called Emily, for help with Latin; and various betatesters including Peter Berman, Doug Jones and Nick Montfort. Also, to L. Ross Raszewski for his wonderful Hints.h hint library. You are granted unconditional right to freely copy and distribute this game, in any form, as long as it remains unaltered. This includes the right to commercial redistribution. If you obtained this game on a CD-ROM, or as part of any other commercial distribution, you should be aware that you do not owe the author or any other entity anything for playing or copying it. The latest version of this game, including any bug-fixes or enhancements made since the Competition, can be found online, in the Interactive Fiction archive at ftp://ftp.gmd.de/if-archive. Along with every other piece of free IF known to humanity - but that\'s another adventure, and you\'ll probably need a guide, as the gmd.de archive is BIG and has lots of dark windy tunnels. Many a nostalgic websurfer has gone in and never been seen again. We try to warn them, but... If you have difficulty finding the latest version, or you would simply like to talk to a human about this game, post a message on the Usenet newsgroup rec.games.int-fiction, or failing that, feel free to email the author. Dedicated to: Alex. Want corknut! Awwk! [SEP]'
# print(model.generate(string, k=30))

from lm import BART2LM

model = BART2LM("./calm/finetune/models/bart/model/epoch00/")
print(model.generate("[CLS] observation [SEP] action [SEP] next observation [SEP]", k=30))
string = '[CLS] You are at the start of your journey. [SEP] begin journey [SEP] NEVERMORE An Interactive Gothic by Nate Cull, 2000. Type ABOUT for instructions. Release 10 / Serial number 000928 / Inform v6.21 Library 6/10 Study (on the velvet couch) Stone walls, wreathed in shadows and velvet curtains, rise into the gloom overhead. The old oak writing desk -- once your father\'s, now your own -- is wedged beneath the window lattice, with a velvet couch before it. A low fire smoulders in its ancient hearth. To the southeast, a bust of Pallas sits atop an arch with darkness beyond. NEVERMORE is a work of Interactive Fiction by Nate Cull (culln@xtra.co.nz), written for the 2000 IF Competition, and based very loosely on the poem "The Raven" by Edgar Allan Poe. All box quotes are from the www.eserver.org text of the poem. Everything else is original, bears no relation to any known literary work or historical fact, and is quite probably indicative of some deep unresolved psychological trauma in the author\'s childhood. For help at any time, type HINT. To see if the game is still winnable, type WINNABLE. Thanks to: the ifMUD gang at http://ifmud.port4000.com for support with Inform coding lore and a constant supply of monkey jokes; Admiral Jota and the Emily who is not called Emily, for help with Latin; and various betatesters including Peter Berman, Doug Jones and Nick Montfort. Also, to L. Ross Raszewski for his wonderful Hints.h hint library. You are granted unconditional right to freely copy and distribute this game, in any form, as long as it remains unaltered. This includes the right to commercial redistribution. If you obtained this game on a CD-ROM, or as part of any other commercial distribution, you should be aware that you do not owe the author or any other entity anything for playing or copying it. The latest version of this game, including any bug-fixes or enhancements made since the Competition, can be found online, in the Interactive Fiction archive at ftp://ftp.gmd.de/if-archive. Along with every other piece of free IF known to humanity - but that\'s another adventure, and you\'ll probably need a guide, as the gmd.de archive is BIG and has lots of dark windy tunnels. Many a nostalgic websurfer has gone in and never been seen again. We try to warn them, but... If you have difficulty finding the latest version, or you would simply like to talk to a human about this game, post a message on the Usenet newsgroup rec.games.int-fiction, or failing that, feel free to email the author. Dedicated to: Alex. Want corknut! Awwk! [SEP]'
#print(model.generate(string, k=30))